### ISSUE TITLE
Have multiple class names.

### ISSUE THREAD

**Issue by ThorinDev** [ThorinDev/MinecraftColorCodes#6]
I would like for a person to either write class="darkblue" or class="&1". And for that to reference the same class. Is this possible?

**Comment by ThorinDev** [comment]
Sort of like this.
`<div class="darkblue"></div> or <div class="&1></div>`

**Comment by yrsegal** [comment]
why not just style them the same way >.>

**Comment by ThorinDev** [comment]
@yrsegal That would make no sense, and make the code bigger ie worse.
